import type { StandupRepository } from '../../core/ports/StandupRepository';
import type { StandupSummary, TaskSummary } from '../../core/domain/types';
import { getNotionClient } from '../../notion/client';
import { config } from '../../config/index';
import { todayISO } from '../../utils/dateHelpers';
import { withRetry, isNotionRateLimit } from '../../utils/retry';

type RichTextItem = {
  type: 'text';
  text: { content: string; link?: { url: string } | null };
  annotations?: {
    bold?: boolean;
    italic?: boolean;
    code?: boolean;
    color?: string;
  };
};

type Block =
  | { object: 'block'; type: 'callout'; callout: { rich_text: RichTextItem[]; icon: { type: 'emoji'; emoji: string }; color: string } }
  | { object: 'block'; type: 'bulleted_list_item'; bulleted_list_item: { rich_text: RichTextItem[]; color?: string } }
  | { object: 'block'; type: 'divider'; divider: Record<string, never> }
  | { object: 'block'; type: 'paragraph'; paragraph: { rich_text: RichTextItem[] } };

function callout(emoji: string, text: string, color: string): Block {
  return {
    object: 'block',
    type: 'callout',
    callout: {
      rich_text: [{ type: 'text', text: { content: text } }],
      icon: { type: 'emoji', emoji },
      color,
    },
  };
}

function linkedBullet(text: string, url?: string): Block {
  const richText: RichTextItem[] = [
    { type: 'text', text: { content: text } },
  ];

  if (url) {
    richText.push({
      type: 'text',
      text: { content: ' ↗', link: { url } },
      annotations: { color: 'gray' },
    });
  }

  return {
    object: 'block',
    type: 'bulleted_list_item',
    bulleted_list_item: { rich_text: richText },
  };
}

function divider(): Block {
  return { object: 'block', type: 'divider', divider: {} };
}

function paragraph(text: string, italic = false): Block {
  return {
    object: 'block',
    type: 'paragraph',
    paragraph: {
      rich_text: [{
        type: 'text',
        text: { content: text },
        annotations: { italic, color: 'gray' },
      }],
    },
  };
}

// Match a bullet text to a task by looking for the task title as a substring
function findTaskUrl(bullet: string, tasks: TaskSummary[]): string | undefined {
  const lower = bullet.toLowerCase();
  const match = tasks.find((t) => lower.includes(t.title.toLowerCase().slice(0, 20)));
  return match?.url;
}

export class NotionStandupRepository implements StandupRepository {
  async writeStandup(summary: StandupSummary, completed: TaskSummary[], active: TaskSummary[]): Promise<string> {
    const notion = getNotionClient();
    const today = todayISO();
    const allTasks = [...completed, ...active];
    const taskCount = allTasks.length;

    const yesterdayBullets = summary.yesterday.length > 0
      ? summary.yesterday.map((b) => linkedBullet(b, findTaskUrl(b, completed)))
      : [linkedBullet('Nothing completed yesterday.')];

    const todayBullets = summary.today.length > 0
      ? summary.today.map((b) => linkedBullet(b, findTaskUrl(b, active)))
      : [linkedBullet('Nothing planned for today.')];

    const blockerBullets = summary.blockers.length > 0
      ? summary.blockers.map((b) => linkedBullet(b, findTaskUrl(b, active)))
      : [linkedBullet('No blockers.')];

    const response = await withRetry(
      () => notion.pages.create({
        parent: { database_id: config.notion.standupLogDbId },
        properties: {
          Title: { title: [{ type: 'text', text: { content: `Standup — ${today}` } }] },
          Date: { date: { start: today } },
          Status: { select: { name: 'Generated' } },
          'Tasks Reviewed': { number: taskCount },
        },
        children: [
          callout('📊', `${completed.length} completed · ${active.length} active · ${summary.blockers.length} blocker${summary.blockers.length !== 1 ? 's' : ''}`, 'gray_background'),
          divider(),
          callout('✅', 'Yesterday', 'green_background'),
          ...yesterdayBullets,
          callout('🔨', 'Today', 'blue_background'),
          ...todayBullets,
          callout('🚧', 'Blockers', summary.blockers.length > 0 ? 'red_background' : 'gray_background'),
          ...blockerBullets,
          divider(),
          paragraph(`Generated by Notion of Progress · ${new Date().toLocaleTimeString()}`, true),
        ],
      }),
      { attempts: 3, delayMs: 1000, shouldRetry: isNotionRateLimit }
    );

    if (!('url' in response)) throw new Error('Unexpected partial response from Notion');
    return response.url;
  }

  async writeFailedStandup(error: string): Promise<void> {
    try {
      const notion = getNotionClient();
      const today = todayISO();
      await notion.pages.create({
        parent: { database_id: config.notion.standupLogDbId },
        properties: {
          Title: { title: [{ type: 'text', text: { content: `Standup — ${today} (Failed)` } }] },
          Date: { date: { start: today } },
          Status: { select: { name: 'Failed' } },
          'Tasks Reviewed': { number: 0 },
        },
        children: [
          callout('❌', `Standup generation failed: ${error}`, 'red_background'),
        ],
      });
    } catch {
      // Best effort — don't throw if the failure page itself fails
    }
  }
}
