import type { StandupRepository } from '../../core/ports/StandupRepository';
import type { StandupSummary, StandupBullet, TaskSummary } from '../../core/domain/types';
import { getNotionClient } from '../../notion/client';
import { config } from '../../config/index';
import { todayISO, todayFormatted } from '../../utils/dateHelpers';
import { withRetry, isNotionRateLimit } from '../../utils/retry';
import type { Client } from '@notionhq/client';

type CreatePageParams = Parameters<Client['pages']['create']>[0];
type BlockRequest = NonNullable<CreatePageParams['children']>[number];
type RichText = Extract<BlockRequest, { type?: 'paragraph' }>['paragraph']['rich_text'][number];
type ApiColor = 'default' | 'gray' | 'brown' | 'orange' | 'yellow' | 'green' | 'blue' | 'purple' | 'pink' | 'red'
  | 'default_background' | 'gray_background' | 'brown_background' | 'orange_background' | 'yellow_background'
  | 'green_background' | 'blue_background' | 'purple_background' | 'pink_background' | 'red_background';

const PAGE_ICONS = [
  '🌅', '☀️', '⚡', '🧠', '🚀', '🎯', '🔥', '💡', '🌿', '🛠️',
  '🌊', '🎸', '🦋', '🌈', '🍀', '🏔️', '🎨', '🦁', '🌙', '✨',
  '🐉', '🎲', '🧩', '🌺', '⚙️', '🦅', '🎪', '🍉', '🔮', '🌍',
];

function randomIcon(): string {
  return PAGE_ICONS[Math.floor(Math.random() * PAGE_ICONS.length)];
}

function richText(content: string, url?: string, opts: { italic?: boolean; color?: ApiColor } = {}): RichText {
  return {
    type: 'text',
    text: { content, link: url ? { url } : null },
    annotations: {
      ...(opts.italic ? { italic: true } : {}),
      ...(opts.color ? { color: opts.color } : {}),
    },
  } as RichText;
}

function callout(emoji: string, content: string, color: string): BlockRequest {
  return {
    type: 'callout',
    callout: {
      rich_text: [richText(content)],
      icon: { type: 'emoji', emoji } as { type: 'emoji'; emoji: never },
      color,
    },
  } as BlockRequest;
}

function linkedBullet(bullet: StandupBullet, taskIndex: Map<string, TaskSummary>): BlockRequest {
  const task = bullet.taskId ? taskIndex.get(bullet.taskId) : undefined;
  const parts: RichText[] = [richText(bullet.text)];

  if (task?.url) {
    parts.push(richText(' ↗', task.url, { color: 'gray' }));
  }

  return {
    type: 'bulleted_list_item',
    bulleted_list_item: { rich_text: parts },
  } as BlockRequest;
}

function divider(): BlockRequest {
  return { type: 'divider', divider: {} } as BlockRequest;
}

function paragraph(content: string, italic = false): BlockRequest {
  return {
    type: 'paragraph',
    paragraph: { rich_text: [richText(content, undefined, { italic, color: 'gray' })] },
  } as BlockRequest;
}

export class NotionStandupRepository implements StandupRepository {
  async findTodayPageId(): Promise<string | null> {
    const notion = getNotionClient();
    const response = await notion.databases.query({
      database_id: config.notion.standupLogDbId,
      filter: { property: 'Date', date: { equals: todayISO() } },
      page_size: 1,
    });
    return response.results[0]?.id ?? null;
  }

  async writeStandup(summary: StandupSummary, completed: TaskSummary[], active: TaskSummary[], existingPageId?: string): Promise<string> {
    const notion = getNotionClient();
    const today = todayISO();
    const allTasks = [...completed, ...active];
    const taskCount = allTasks.length;
    const taskIndex = new Map(allTasks.map((t) => [t.id, t]));

    const noBullet = (content: string): BlockRequest => linkedBullet({ text: content }, taskIndex);

    const yesterdayBullets = summary.yesterday.length > 0
      ? summary.yesterday.map((b) => linkedBullet(b, taskIndex))
      : [noBullet('Nothing completed yesterday.')];

    const todayBullets = summary.today.length > 0
      ? summary.today.map((b) => linkedBullet(b, taskIndex))
      : [noBullet('Nothing planned for today.')];

    const blockerBullets = summary.blockers.length > 0
      ? summary.blockers.map((b) => linkedBullet(b, taskIndex))
      : [noBullet('No blockers.')];

    const children: BlockRequest[] = [
      callout('📊', `${completed.length} completed · ${active.length} active · ${summary.blockers.length} blocker${summary.blockers.length !== 1 ? 's' : ''}`, 'gray_background'),
      divider(),
      callout('✅', 'Yesterday', 'green_background'),
      ...yesterdayBullets,
      callout('🔨', 'Today', 'blue_background'),
      ...todayBullets,
      callout('🚧', 'Blockers', summary.blockers.length > 0 ? 'red_background' : 'gray_background'),
      ...blockerBullets,
      divider(),
      paragraph(`Generated by Notion of Progress · ${new Date().toLocaleTimeString()}`, true),
    ];

    const properties = {
      Title: { title: [{ type: 'text' as const, text: { content: `Standup · ${todayFormatted()}` } }] },
      Date: { date: { start: today } },
      Status: { select: { name: 'Generated' } },
      'Tasks Reviewed': { number: taskCount },
    };

    if (existingPageId) {
      // Clear existing blocks then append fresh content
      const existingBlocks = await notion.blocks.children.list({ block_id: existingPageId });
      await Promise.all(existingBlocks.results.map((b) => notion.blocks.delete({ block_id: b.id })));

      const response = await withRetry(
        () => notion.pages.update({
          page_id: existingPageId,
          properties,
        }),
        { attempts: 3, delayMs: 1000, shouldRetry: isNotionRateLimit }
      );
      await notion.blocks.children.append({ block_id: existingPageId, children });
      if (!('url' in response)) throw new Error('Unexpected partial response from Notion');
      return response.url;
    }

    const response = await withRetry(
      () => notion.pages.create({
        parent: { database_id: config.notion.standupLogDbId },
        icon: { type: 'emoji', emoji: randomIcon() as never },
        properties,
        children,
      }),
      { attempts: 3, delayMs: 1000, shouldRetry: isNotionRateLimit }
    );

    if (!('url' in response)) throw new Error('Unexpected partial response from Notion');
    return response.url;
  }

  async writeFailedStandup(error: string): Promise<void> {
    try {
      const notion = getNotionClient();
      const today = todayISO();
      await notion.pages.create({
        parent: { database_id: config.notion.standupLogDbId },
        properties: {
          Title: { title: [{ type: 'text', text: { content: `Standup — ${today} (Failed)` } }] },
          Date: { date: { start: today } },
          Status: { select: { name: 'Failed' } },
          'Tasks Reviewed': { number: 0 },
        },
        children: [
          callout('❌', `Standup generation failed: ${error}`, 'red_background'),
        ],
      });
    } catch {
      // Best effort — don't throw if the failure page itself fails
    }
  }
}
