/**
 * Tests for Discord notification functionality
 * 
 * Tests the Discord webhook integration for standup notifications,
 * including message formatting, error handling, and field truncation.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import type { StandupSummary } from '../src/core/domain/types';

// Mock the config
const mockConfig = {
  discord: {
    webhookUrl: null as string | null,
  },
};

vi.mock('../src/config/index', () => ({
  config: mockConfig,
}));

vi.mock('../src/utils/logger', () => ({
  logger: {
    info: vi.fn(),
    warn: vi.fn(),
  },
}));

// Mock global fetch
const mockFetch = vi.fn();
global.fetch = mockFetch;

describe('Discord Notifier', () => {
  const mockSummary: StandupSummary = {
    yesterday: [{ text: 'Completed authentication module' }],
    today: [{ text: 'Start notification system' }],
    blockers: [],
  };

  const mockUrl = 'https://notion.so/standup-123';
  const mockDate = '2026-03-18';

  beforeEach(() => {
    vi.clearAllMocks();
    mockConfig.discord.webhookUrl = 'https://discord.com/api/webhooks/123/abc';
    mockFetch.mockResolvedValue({
      ok: true,
      status: 200,
    });
  });

  afterEach(() => {
    mockConfig.discord.webhookUrl = null;
  });

  describe('notifyDiscord', () => {
    it('should send notification when webhook URL is configured', async () => {
      // Arrange
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');

      // Act
      await notifyDiscord(mockSummary, mockUrl, mockDate);

      // Assert
      expect(mockFetch).toHaveBeenCalledOnce();
      expect(mockFetch).toHaveBeenCalledWith(
        'https://discord.com/api/webhooks/123/abc',
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: expect.stringContaining('📋 Standup · 2026-03-18'),
        }
      );
    });

    it('should skip notification when webhook URL is not configured', async () => {
      // Arrange
      mockConfig.discord.webhookUrl = null;
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');

      // Act
      await notifyDiscord(mockSummary, mockUrl, mockDate);

      // Assert
      expect(mockFetch).not.toHaveBeenCalled();
    });

    it('should format message with correct structure', async () => {
      // Arrange
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');

      // Act
      await notifyDiscord(mockSummary, mockUrl, mockDate);

      // Assert
      expect(mockFetch).toHaveBeenCalledWith(
        expect.any(String),
        expect.objectContaining({
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: expect.any(String),
        })
      );

      const requestBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      expect(requestBody).toMatchObject({
        embeds: [{
          title: '📋 Standup · 2026-03-18',
          color: 0x2ecc71,
          fields: [
            { name: '✅ Yesterday', value: '• Completed authentication module', inline: false },
            { name: '🔨 Today', value: '• Start notification system', inline: false },
            { name: '🚧 Blockers', value: '• Nothing to report.', inline: false },
          ],
          footer: { text: 'Generated by Notion of Progress' },
          url: mockUrl,
        }],
      });
    });

    it('should handle empty sections gracefully', async () => {
      // Arrange
      const emptySummary: StandupSummary = {
        yesterday: [],
        today: [],
        blockers: [],
      };
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');

      // Act
      await notifyDiscord(emptySummary, mockUrl, mockDate);

      // Assert
      const requestBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      expect(requestBody.embeds[0].fields).toEqual([
        { name: '✅ Yesterday', value: '• Nothing to report.', inline: false },
        { name: '🔨 Today', value: '• Nothing to report.', inline: false },
        { name: '🚧 Blockers', value: '• Nothing to report.', inline: false },
      ]);
    });

    it('should handle multiple items in each section', async () => {
      // Arrange
      const richSummary: StandupSummary = {
        yesterday: [
          { text: 'Completed authentication module' },
          { text: 'Fixed critical bug in payment system' },
        ],
        today: [
          { text: 'Start notification system' },
          { text: 'Review pull requests' },
          { text: 'Deploy to staging' },
        ],
        blockers: [
          { text: 'Waiting for API documentation' },
        ],
      };
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');

      // Act
      await notifyDiscord(richSummary, mockUrl, mockDate);

      // Assert
      const requestBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      expect(requestBody.embeds[0].fields[0].value).toBe(
        '• Completed authentication module\n• Fixed critical bug in payment system'
      );
      expect(requestBody.embeds[0].fields[1].value).toBe(
        '• Start notification system\n• Review pull requests\n• Deploy to staging'
      );
      expect(requestBody.embeds[0].fields[2].value).toBe('• Waiting for API documentation');
    });

    it('should truncate long messages to Discord field limits', async () => {
      // Arrange
      const longText = 'A'.repeat(1500); // Exceeds 1024 limit
      const longSummary: StandupSummary = {
        yesterday: [{ text: longText }],
        today: [{ text: 'Normal task' }],
        blockers: [],
      };
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');

      // Act
      await notifyDiscord(longSummary, mockUrl, mockDate);

      // Assert
      const requestBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      const yesterdayValue = requestBody.embeds[0].fields[0].value;
      
      expect(yesterdayValue.length).toBeLessThanOrEqual(1024);
      expect(yesterdayValue.endsWith('…')).toBe(true);
      expect(yesterdayValue.startsWith('• A')).toBe(true);
    });

    it('should handle Discord webhook errors gracefully', async () => {
      // Arrange
      mockFetch.mockResolvedValue({
        ok: false,
        status: 400,
        text: async () => 'Bad Request: Invalid webhook',
      });
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');

      // Act & Assert - Should not throw
      await expect(notifyDiscord(mockSummary, mockUrl, mockDate)).resolves.toBeUndefined();

      // Should have called fetch but handled the error gracefully
      expect(mockFetch).toHaveBeenCalledOnce();
    });

    it('should handle network errors gracefully', async () => {
      // Arrange
      mockFetch.mockRejectedValue(new Error('Network error'));
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');

      // Act & Assert - Should not throw
      await expect(notifyDiscord(mockSummary, mockUrl, mockDate)).rejects.toThrow('Network error');
    });

    it('should handle malformed webhook URL by making the request', async () => {
      // Arrange
      mockConfig.discord.webhookUrl = 'invalid-url';
      mockFetch.mockRejectedValue(new TypeError('Invalid URL'));
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');

      // Act & Assert - Should attempt the call and throw since URL is invalid
      await expect(notifyDiscord(mockSummary, mockUrl, mockDate)).rejects.toThrow();
    });
  });

  describe('message formatting edge cases', () => {
    it('should handle special characters in content', async () => {
      // Arrange
      const specialSummary: StandupSummary = {
        yesterday: [{ text: 'Fixed bug with "quotes" & <html> tags' }],
        today: [{ text: 'Work on @mentions and #hashtags' }],
        blockers: [{ text: 'API returns 500 error 💥' }],
      };
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');

      // Act
      await notifyDiscord(specialSummary, mockUrl, mockDate);

      // Assert - Should handle special characters without errors
      expect(mockFetch).toHaveBeenCalledOnce();
      const requestBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      expect(requestBody.embeds[0].fields[0].value).toContain('Fixed bug with "quotes" & <html> tags');
      expect(requestBody.embeds[0].fields[1].value).toContain('Work on @mentions and #hashtags');
      expect(requestBody.embeds[0].fields[2].value).toContain('API returns 500 error 💥');
    });

    it('should format dates consistently', async () => {
      // Arrange
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');
      const testDate = '2026-12-25';

      // Act
      await notifyDiscord(mockSummary, mockUrl, testDate);

      // Assert
      const requestBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      expect(requestBody.embeds[0].title).toBe('📋 Standup · 2026-12-25');
    });

    it('should preserve URL in embed', async () => {
      // Arrange
      const { notifyDiscord } = await import('../src/adapters/discord/DiscordNotifier');
      const testUrl = 'https://custom.notion.site/standup-456';

      // Act
      await notifyDiscord(mockSummary, testUrl, mockDate);

      // Assert
      const requestBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      expect(requestBody.embeds[0].url).toBe(testUrl);
    });
  });
});