import { config } from '../../config/index';
import { logger } from '../../utils/logger';
import type { StandupSummary } from '../../core/domain/types';

function buildMessage(summary: StandupSummary, url: string, date: string): object {
  const fmt = (bullets: Array<{ text: string }>) =>
    bullets.length > 0 ? bullets.map((b) => `• ${b.text}`).join('\n') : '• Nothing to report.';

  return {
    embeds: [
      {
        title: `📋 Standup · ${date}`,
        color: 0x2ecc71,
        fields: [
          { name: '✅ Yesterday', value: fmt(summary.yesterday), inline: false },
          { name: '🔨 Today', value: fmt(summary.today), inline: false },
          { name: '🚧 Blockers', value: fmt(summary.blockers), inline: false },
        ],
        footer: { text: 'Generated by Notion of Progress' },
        url,
      },
    ],
  };
}

export async function notifyDiscord(
  summary: StandupSummary,
  url: string,
  date: string,
): Promise<void> {
  if (!config.discord.webhookUrl) {
    logger.info('Discord webhook not configured — skipping notification');
    return;
  }

  const response = await fetch(config.discord.webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(buildMessage(summary, url, date)),
  });

  if (!response.ok) {
    const text = await response.text();
    logger.warn(`Discord notification failed: ${response.status} ${text}`);
    return;
  }

  logger.info('Discord notification sent');
}
