// Core orchestrator: taskReader → summarizer → standupWriter

import { fetchTasks } from './taskReader';
import { generateSummary } from './summarizer';
import { writeStandup } from './standupWriter';
import { logger } from '../utils/logger';
import { todayISO } from '../utils/dateHelpers';

export async function runStandup(): Promise<void> {
  logger.info(`Running standup for ${todayISO()}`);

  const { completed, active } = await fetchTasks();
  logger.info(`Fetched ${completed.length} completed, ${active.length} active tasks`);

  const summary = await generateSummary(completed, active);
  logger.info('Summary generated by Claude');

  const pageUrl = await writeStandup(summary, completed.length + active.length);
  logger.info(`Standup written to Notion: ${pageUrl}`);
}
