import { getNotionClient } from '../notion/client';
import { config } from '../config/index';
import { todayISO } from '../utils/dateHelpers';
import type { StandupSummary } from '../notion/types';

function bulletBlocks(items: string[]) {
  if (items.length === 0) {
    return [
      {
        object: 'block' as const,
        type: 'bulleted_list_item' as const,
        bulleted_list_item: {
          rich_text: [{ type: 'text' as const, text: { content: 'Nothing to report.' } }],
        },
      },
    ];
  }

  return items.map((item) => ({
    object: 'block' as const,
    type: 'bulleted_list_item' as const,
    bulleted_list_item: {
      rich_text: [{ type: 'text' as const, text: { content: item } }],
    },
  }));
}

function heading(text: string) {
  return {
    object: 'block' as const,
    type: 'heading_2' as const,
    heading_2: {
      rich_text: [{ type: 'text' as const, text: { content: text } }],
    },
  };
}

function divider() {
  return { object: 'block' as const, type: 'divider' as const, divider: {} };
}

function paragraph(text: string) {
  return {
    object: 'block' as const,
    type: 'paragraph' as const,
    paragraph: {
      rich_text: [
        {
          type: 'text' as const,
          text: { content: text },
          annotations: { italic: true, bold: false, strikethrough: false, underline: false, code: false, color: 'default' as const },
        },
      ],
    },
  };
}

export async function writeStandup(
  summary: StandupSummary,
  taskCount: number
): Promise<string> {
  const notion = getNotionClient();
  const today = todayISO();
  const title = `Standup — ${today}`;

  const response = await notion.pages.create({
    parent: { database_id: config.notion.standupLogDbId },
    properties: {
      Title: {
        title: [{ type: 'text', text: { content: title } }],
      },
      Date: {
        date: { start: today },
      },
      Status: {
        select: { name: 'Generated' },
      },
      'Tasks Reviewed': {
        number: taskCount,
      },
    },
    children: [
      heading('Yesterday'),
      ...bulletBlocks(summary.yesterday),
      heading('Today'),
      ...bulletBlocks(summary.today),
      heading('Blockers'),
      ...bulletBlocks(summary.blockers),
      divider(),
      paragraph(`Generated by Notion of Progress at ${new Date().toLocaleTimeString()}`),
    ],
  });

  if (!('url' in response)) throw new Error('Unexpected partial response from Notion');
  return response.url;
}
