/**
 * scripts/setup.ts
 *
 * Unified setup script for Notion of Progress.
 * 
 * This script handles all setup tasks:
 *   1. Creates Notion databases (Task DB, Standup Log, System Status)
 *   2. Configures GitHub repository secrets for automated deployment
 *   3. Validates environment configuration
 *   4. Provides next steps and guidance
 *
 * Usage:
 *   npm run setup
 *   
 * Prerequisites:
 *   1. Create an integration at https://www.notion.com/my-integrations
 *   2. Create an empty page in Notion (e.g. "Notion of Progress")
 *   3. Connect your integration to that page: ··· → Connections
 *   4. Set NOTION_API_KEY and ANTHROPIC_API_KEY in .env
 *
 * The script will ask for the Notion page URL and handle the rest automatically.
 * It's idempotent - safe to run multiple times, only creates missing resources.
 */

import 'dotenv/config';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createInterface } from 'readline';
import { Client } from '@notionhq/client';

// Dashboard icons for status pages
const DASHBOARD_ICONS = ['🚀', '💻', '⚡', '🔧', '📊', '🤖', '⚙️', '💡', '🎯', '🔥'] as const;

function randomDashboardIcon(): string {
  return DASHBOARD_ICONS[Math.floor(Math.random() * DASHBOARD_ICONS.length)];
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ENV_PATH = join(ROOT, '.env');

interface SecretConfig {
  name: string;
  value: string | undefined;
  required: boolean;
  description: string;
}

function prompt(question: string): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function extractPageId(input: string): string {
  // Handle full Notion URLs: https://www.notion.so/Page-Title-abc123def456
  // or bare UUIDs: abc123de-f456-...
  const urlMatch = input.match(/([a-f0-9]{32})(?:\?|$)/i) || input.match(/([a-f0-9-]{36})(?:\?|$)/i);
  if (urlMatch) return urlMatch[1].replace(/-/g, '');
  // Try stripping dashes from bare UUID
  const bare = input.replace(/-/g, '');
  if (/^[a-f0-9]{32}$/i.test(bare)) return bare;
  throw new Error(`Could not extract a page ID from: "${input}"`);
}

function updateEnv(key: string, value: string): void {
  let content = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, 'utf8') : '';
  const line = `${key}=${value}`;
  const regex = new RegExp(`^#?\\s*${key}=.*`, 'm');

  if (regex.test(content)) {
    content = content.replace(regex, line);
  } else {
    content = content.trimEnd() + `\n${line}\n`;
  }

  writeFileSync(ENV_PATH, content, 'utf8');
}

function getRequiredSecrets(): SecretConfig[] {
  return [
    {
      name: 'NOTION_API_KEY',
      value: process.env.NOTION_API_KEY,
      required: true,
      description: 'Notion integration token from https://www.notion.com/my-integrations'
    },
    {
      name: 'ANTHROPIC_API_KEY', 
      value: process.env.ANTHROPIC_API_KEY,
      required: true,
      description: 'Anthropic API key from https://console.anthropic.com/settings/keys'
    },
    {
      name: 'NOTION_TASK_DB_ID',
      value: process.env.NOTION_TASK_DB_ID,
      required: true,
      description: 'Task database ID (auto-generated by setup script)'
    },
    {
      name: 'NOTION_STANDUP_LOG_DB_ID',
      value: process.env.NOTION_STANDUP_LOG_DB_ID,
      required: true,
      description: 'Standup log database ID (auto-generated by setup script)'
    },
    {
      name: 'NOTION_SYSTEM_STATUS_DB_ID',
      value: process.env.NOTION_SYSTEM_STATUS_DB_ID,
      required: true,
      description: 'System status database ID (auto-generated by setup script)'
    },
    {
      name: 'DISCORD_WEBHOOK_URL',
      value: process.env.DISCORD_WEBHOOK_URL,
      required: false,
      description: 'Discord webhook URL for notifications (optional)'
    }
  ];
}

async function checkGitHubCLI(): Promise<boolean> {
  try {
    const { execSync } = await import('child_process');
    execSync('gh --version', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

async function checkGitHubRepo(): Promise<{ owner: string; repo: string } | null> {
  try {
    const { execSync } = await import('child_process');
    const remoteUrl = execSync('git remote get-url origin', { encoding: 'utf8' }).trim();
    
    // Parse GitHub URL (both HTTPS and SSH formats)
    const httpsMatch = remoteUrl.match(/https:\/\/github\.com\/([^\/]+)\/([^\/]+?)(?:\.git)?$/);
    const sshMatch = remoteUrl.match(/git@github\.com:([^\/]+)\/([^\/]+?)(?:\.git)?$/);
    
    if (httpsMatch) {
      return { owner: httpsMatch[1], repo: httpsMatch[2] };
    } else if (sshMatch) {
      return { owner: sshMatch[1], repo: sshMatch[2] };
    }
    
    return null;
  } catch {
    return null;
  }
}

async function createTaskDB(notion: Client, parentPageId: string): Promise<string> {
  console.log('  Creating Task DB...');
  const response = await notion.databases.create({
    parent: { type: 'page_id', page_id: parentPageId },
    title: [{ type: 'text', text: { content: 'Task DB' } }],
    properties: {
      Name: { title: {} },
      Status: {
        select: {
          options: [
            { name: 'To Do', color: 'red' },
            { name: 'In Progress', color: 'yellow' },
            { name: 'Done', color: 'green' },
            { name: 'Blocked', color: 'orange' },
          ],
        },
      },
      Priority: {
        select: {
          options: [
            { name: 'High', color: 'red' },
            { name: 'Medium', color: 'yellow' },
            { name: 'Low', color: 'gray' },
          ],
        },
      },
      'Due Date': { date: {} },
      Notes: { rich_text: {} },
      Assignee: { people: {} },
    },
  });
  console.log(`  Task DB created ✓`);
  return response.id;
}

async function createStandupLogDB(notion: Client, parentPageId: string): Promise<string> {
  console.log('  Creating Standup Log DB...');
  const response = await notion.databases.create({
    parent: { type: 'page_id', page_id: parentPageId },
    title: [{ type: 'text', text: { content: 'Standup Log' } }],
    properties: {
      Title: { title: {} },
      Date: { date: {} },
      Status: {
        select: {
          options: [
            { name: 'Generated', color: 'green' },
            { name: 'Draft', color: 'yellow' },
            { name: 'Failed', color: 'red' },
          ],
        },
      },
      'Tasks Reviewed': { number: { format: 'number' } },
    },
  });
  console.log(`  Standup Log created ✓`);
  return response.id;
}

async function createSystemStatusDB(notion: Client, parentPageId: string): Promise<string> {
  console.log('  Creating System Status DB...');
  const response = await notion.databases.create({
    parent: { type: 'page_id', page_id: parentPageId },
    title: [{ type: 'text', text: { content: 'System Status' } }],
    properties: {
      Title: { title: {} },
      'Last Run': { date: {} },
      Status: {
        select: {
          options: [
            { name: 'Operational', color: 'green' },
            { name: 'Degraded', color: 'yellow' },
            { name: 'Down', color: 'red' },
          ],
        },
      },
      'Total Standups': { number: { format: 'number' } },
      Environment: { rich_text: {} },
    },
  });
  console.log(`  System Status DB created ✓`);
  
  // Create initial status page so users see the dashboard immediately
  console.log('  Creating initial status page...');
  await createInitialStatusPage(notion, response.id);
  console.log(`  Initial status page created ✓`);
  
  return response.id;
}

async function createInitialStatusPage(notion: Client, systemStatusDbId: string): Promise<void> {
  const now = new Date();
  const today = now.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  await notion.pages.create({
    parent: { type: 'database_id', database_id: systemStatusDbId },
    icon: { type: 'emoji', emoji: randomDashboardIcon() as never },
    properties: {
      Title: {
        title: [{ type: 'text', text: { content: `🚀 System Dashboard - ${today}` } }],
      },
      'Last Run': {
        date: { start: now.toISOString() },
      },
      Status: {
        select: { name: 'Operational' },
      },
      'Total Standups': {
        number: 0,
      },
      Environment: {
        rich_text: [{ type: 'text', text: { content: 'Setup Complete' } }],
      },
    },
    children: [
      // Hero header
      {
        type: 'callout',
        callout: {
          rich_text: [{ type: 'text', text: { content: '🤖 Notion of Progress AI Agent' }, annotations: { bold: true } }],
          icon: { type: 'emoji', emoji: '🚀' },
          color: 'blue_background',
        },
      },
      {
        type: 'paragraph',
        paragraph: {
          rich_text: [{ type: 'text', text: { content: '🔥 LIVE SYSTEM DASHBOARD 🔥' }, annotations: { bold: true } }],
        },
      },
      // Status
      {
        type: 'callout',
        callout: {
          rich_text: [{ type: 'text', text: { content: '🟢 System Status: Ready for First Run' }, annotations: { bold: true } }],
          icon: { type: 'emoji', emoji: '🟢' },
          color: 'green_background',
        },
      },
      // Setup message
      {
        type: 'callout',
        callout: {
          rich_text: [{ type: 'text', text: { content: '📋 Setup completed successfully! Run your first standup to see live metrics.' }, annotations: { bold: true } }],
          icon: { type: 'emoji', emoji: '✅' },
          color: 'purple_background',
        },
      },
      {
        type: 'paragraph',
        paragraph: {
          rich_text: [
            { type: 'text', text: { content: '🚀 Next Steps: ' }, annotations: { bold: true } },
            { type: 'text', text: { content: 'Run ' }, annotations: {} },
            { type: 'text', text: { content: 'npm run standup' }, annotations: { code: true } },
            { type: 'text', text: { content: ' to generate your first standup and see live operational metrics!' }, annotations: {} },
          ],
        },
      },
      {
        type: 'divider',
        divider: {},
      },
      // Public sharing hint
      {
        type: 'callout',
        callout: {
          rich_text: [{ type: 'text', text: { content: '🌍 Make this page public: Page Settings → Share → Share to web → Anyone with link can view' }, annotations: {} }],
          icon: { type: 'emoji', emoji: '🔗' },
          color: 'blue_background',
        },
      },
      // Footer
      {
        type: 'callout',
        callout: {
          rich_text: [{ type: 'text', text: { content: '✨ Built for the DEV.to Notion MCP Challenge 2026 ✨' }, annotations: { bold: true } }],
          icon: { type: 'emoji', emoji: '🏆' },
          color: 'orange_background',
        },
      },
    ],
  });
}

async function validateDB(notion: Client, dbId: string, name: string, requiredProps: string[]): Promise<void> {
  const db = await notion.databases.retrieve({ database_id: dbId });
  const props = Object.keys(db.properties);
  const missing = requiredProps.filter((p) => !props.includes(p));
  if (missing.length > 0) throw new Error(`${name} is missing properties: ${missing.join(', ')}`);
  console.log(`  ${name} ✓`);
}

async function setSecretsViaGitHubCLI(secrets: SecretConfig[]): Promise<boolean> {
  try {
    const { execSync } = await import('child_process');
    
    console.log('\n🔐 Setting up GitHub secrets...\n');
    
    let allSuccessful = true;
    
    for (const secret of secrets) {
      if (!secret.value) {
        if (secret.required) {
          console.log(`❌ Required secret ${secret.name} is missing from .env`);
          allSuccessful = false;
        } else {
          console.log(`⏭️  Skipping optional secret ${secret.name} (not set in .env)`);
        }
        continue;
      }

      try {
        execSync(`gh secret set ${secret.name} --body "${secret.value}"`, { 
          stdio: 'pipe' 
        });
        console.log(`  ✅ ${secret.name}`);
      } catch (error) {
        console.log(`  ❌ Failed to set ${secret.name}`);
        allSuccessful = false;
      }
    }
    
    return allSuccessful;
  } catch {
    return false;
  }
}

function printManualSecretsInstructions(secrets: SecretConfig[], repoInfo: { owner: string; repo: string } | null): void {
  console.log('\n📖 Manual GitHub Secrets Setup Required\n');
  
  if (repoInfo) {
    console.log(`🔗 Repository: https://github.com/${repoInfo.owner}/${repoInfo.repo}`);
    console.log(`🔧 Secrets URL: https://github.com/${repoInfo.owner}/${repoInfo.repo}/settings/secrets/actions\n`);
  } else {
    console.log('🔧 Go to your GitHub repository → Settings → Secrets and variables → Actions\n');
  }
  
  console.log('📋 Add these repository secrets:\n');
  
  for (const secret of secrets) {
    const status = secret.value ? '✅' : (secret.required ? '❌' : '⏭️');
    const value = secret.value || (secret.required ? 'MISSING - CHECK .env' : 'Not set (optional)');
    
    console.log(`${status} ${secret.name}`);
    console.log(`   Description: ${secret.description}`);
    console.log(`   Value: ${secret.value ? '***[HIDDEN]***' : value}`);
    console.log('');
  }
  
  console.log('💻 GitHub CLI Commands (if you prefer):\n');
  
  for (const secret of secrets) {
    if (secret.value) {
      console.log(`gh secret set ${secret.name} --body "${secret.value}"`);
    } else if (secret.required) {
      console.log(`# ${secret.name} - MISSING FROM .env`);
    } else {
      console.log(`# gh secret set ${secret.name} --body "your_value_here"  # Optional`);
    }
  }
}

async function setupNotionDatabases(): Promise<{ taskDbId: string; standupLogDbId: string; systemStatusDbId: string }> {
  const NOTION_API_KEY = process.env.NOTION_API_KEY;

  if (!NOTION_API_KEY) {
    console.error('\n❌ ERROR: NOTION_API_KEY is not set. Add it to your .env file first.\n');
    console.log('📖 Setup guide:');
    console.log('   1. Create an integration: https://www.notion.com/my-integrations');
    console.log('   2. Copy the integration token to .env as NOTION_API_KEY');
    console.log('   3. Run this setup script again\n');
    process.exit(1);
  }

  const notion = new Client({ auth: NOTION_API_KEY });

  const existingTaskDbId = process.env.NOTION_TASK_DB_ID;
  const existingStandupDbId = process.env.NOTION_STANDUP_LOG_DB_ID;
  const existingSystemStatusDbId = process.env.NOTION_SYSTEM_STATUS_DB_ID;

  // Validate existing databases
  if (existingTaskDbId) {
    console.log('Validating Task DB...');
    await validateDB(notion, existingTaskDbId, 'Task DB', ['Name', 'Status', 'Priority', 'Due Date']);
  }
  
  if (existingStandupDbId) {
    console.log('Validating Standup Log...');
    await validateDB(notion, existingStandupDbId, 'Standup Log', ['Title', 'Date', 'Status', 'Tasks Reviewed']);
  }
  
  if (existingSystemStatusDbId) {
    console.log('Validating System Status...');
    await validateDB(notion, existingSystemStatusDbId, 'System Status', ['Title', 'Last Run', 'Status', 'Total Standups']);
  }
  
  // Check what needs to be created
  const needsTask = !existingTaskDbId;
  const needsStandup = !existingStandupDbId;
  const needsStatus = !existingSystemStatusDbId;
  
  if (!needsTask && !needsStandup && !needsStatus) {
    console.log('\n✅ All Notion databases exist and are valid!\n');
    return {
      taskDbId: existingTaskDbId!,
      standupLogDbId: existingStandupDbId!,
      systemStatusDbId: existingSystemStatusDbId!
    };
  }

  // Show what needs to be created
  console.log('\n🏗️  Creating missing Notion databases:');
  if (needsTask) console.log('  • Task DB — Your daily tasks and projects');
  if (needsStandup) console.log('  • Standup Log — Generated standup summaries');
  if (needsStatus) console.log('  • System Status — Live monitoring dashboard');
  console.log('');

  // Get parent page (either from existing setup or user input)
  let parentPageId: string;
  
  if (existingTaskDbId) {
    // If we have an existing Task DB, get its parent page
    try {
      const taskDb = await notion.databases.retrieve({ database_id: existingTaskDbId }) as any;
      parentPageId = taskDb.parent?.type === 'page_id' ? taskDb.parent.page_id : '';
      if (!parentPageId) throw new Error('Could not find parent page from existing Task DB');
      console.log('Using parent page from existing Task DB ✓\n');
    } catch {
      console.error('❌ Could not find parent page from existing databases. Please provide the page URL.');
      const pageUrl = await prompt('Paste the URL of your Notion parent page: ');
      parentPageId = extractPageId(pageUrl);
    }
  } else {
    // New setup - ask for parent page
    console.log('Before continuing, make sure you have:');
    console.log('  1. Created an empty page in Notion (e.g. "Notion of Progress")');
    console.log('  2. Connected your integration to it: ··· → Connections → <your integration>\n');

    const pageUrl = await prompt('Paste the URL of that Notion page: ');
    try {
      parentPageId = extractPageId(pageUrl);
    } catch (e) {
      console.error(`\n❌ ${(e as Error).message}`);
      process.exit(1);
    }
  }

  // Verify we can access the page
  try {
    await notion.pages.retrieve({ page_id: parentPageId });
    console.log('  Page found ✓\n');
  } catch {
    console.error('\n❌ Could not access that page. Make sure you connected your integration to it.\n');
    process.exit(1);
  }

  // Create only missing databases
  let taskDbId: string = existingTaskDbId || '';
  let standupLogDbId: string = existingStandupDbId || '';
  let systemStatusDbId: string = existingSystemStatusDbId || '';

  if (needsTask) {
    taskDbId = await createTaskDB(notion, parentPageId);
  }
  
  if (needsStandup) {
    standupLogDbId = await createStandupLogDB(notion, parentPageId);
  }
  
  if (needsStatus) {
    systemStatusDbId = await createSystemStatusDB(notion, parentPageId);
  }

  // Update .env with any new IDs
  console.log('\n  Writing DB IDs to .env...');
  if (needsTask) updateEnv('NOTION_TASK_DB_ID', taskDbId);
  if (needsStandup) updateEnv('NOTION_STANDUP_LOG_DB_ID', standupLogDbId);
  if (needsStatus) updateEnv('NOTION_SYSTEM_STATUS_DB_ID', systemStatusDbId);

  console.log('\n✅ Notion databases setup complete!');

  if (needsStatus) {
    console.log('\n📊 The System Status page shows your system\'s live operational status!');
    console.log('\n💡 TIP: Make your System Status page public:');
    console.log('    1. Open the System Status page in Notion');
    console.log('    2. Click "Share" → "Share to web" → "Anyone with link can view"');
    console.log('    3. Copy the public URL and add it to your README!');
  }

  return { taskDbId, standupLogDbId, systemStatusDbId };
}

async function setupGitHubSecrets(): Promise<void> {
  // Check if we have a GitHub repository
  const repoInfo = await checkGitHubRepo();
  if (!repoInfo) {
    console.log('\n⚠️  No GitHub repository detected. GitHub Actions setup skipped.');
    console.log('   To enable automated standups, push your code to GitHub first.\n');
    return;
  }

  console.log(`\n🐙 GitHub repository detected: ${repoInfo.owner}/${repoInfo.repo}`);

  // Get secrets configuration - this will include the fresh database IDs
  const secrets = getRequiredSecrets();
  const missingRequired = secrets.filter(s => s.required && !s.value);

  if (missingRequired.length > 0) {
    console.log('\n❌ Cannot set up GitHub secrets - missing required environment variables.');
    printManualSecretsInstructions(secrets, repoInfo);
    return;
  }

  // Check GitHub CLI availability
  const hasGitHubCLI = await checkGitHubCLI();
  
  if (hasGitHubCLI) {
    console.log('\n🔧 GitHub CLI detected. Setting up repository secrets automatically...');
    const success = await setSecretsViaGitHubCLI(secrets);
    
    if (success) {
      console.log('\n🎉 GitHub secrets setup complete!');
      console.log('\n📋 Your automated workflows are now ready:');
      console.log('   📅 Daily standups: Weekdays at 8 AM EST');
      console.log('   📊 Weekly digest: Fridays at 5 PM EST');
      console.log('\n🧪 Test your setup:');
      console.log('   1. Go to Actions tab in your GitHub repo');
      console.log('   2. Select "Daily Standup Automation"');
      console.log('   3. Click "Run workflow" to test manually');
    } else {
      console.log('\n⚠️  Some secrets failed to set. Please check manually:');
      printManualSecretsInstructions(secrets, repoInfo);
    }
  } else {
    console.log('\n📖 GitHub CLI not found. Manual setup required for automated deployment:');
    printManualSecretsInstructions(secrets, repoInfo);
    console.log('\n💡 Install GitHub CLI: brew install gh (macOS) or npm install -g @github/cli');
  }
}

async function main(): Promise<void> {
  console.log('\n🚀 Notion of Progress — Complete Setup\n');

  // Check for required API keys first
  if (!process.env.NOTION_API_KEY || !process.env.ANTHROPIC_API_KEY) {
    console.log('❌ Missing required API keys in .env file:\n');
    if (!process.env.NOTION_API_KEY) {
      console.log('   NOTION_API_KEY - Get from https://www.notion.com/my-integrations');
    }
    if (!process.env.ANTHROPIC_API_KEY) {
      console.log('   ANTHROPIC_API_KEY - Get from https://console.anthropic.com/settings/keys');
    }
    console.log('\nAdd these to your .env file and run setup again.\n');
    process.exit(1);
  }

  // Step 1: Setup Notion databases
  console.log('📖 STEP 1: Notion Databases');
  const { taskDbId, standupLogDbId, systemStatusDbId } = await setupNotionDatabases();

  console.log('\n  Database URLs:');
  console.log(`  Task DB:        https://www.notion.so/${taskDbId.replace(/-/g, '')}`);
  console.log(`  Standup Log:    https://www.notion.so/${standupLogDbId.replace(/-/g, '')}`);
  console.log(`  System Status:  https://www.notion.so/${systemStatusDbId.replace(/-/g, '')}`);

  // Step 2: Setup GitHub secrets for automation
  console.log('\n🚀 STEP 2: GitHub Actions Setup');
  await setupGitHubSecrets();

  // Final instructions
  console.log('\n✅ SETUP COMPLETE!\n');
  console.log('🎯 Next Steps:');
  console.log('   1. Run your first standup: npm run standup');
  console.log('   2. Check your System Status dashboard in Notion');
  console.log('   3. Make the System Status page public (optional)');
  console.log('   4. Test GitHub Actions workflows (if configured)');
  console.log('\n🔥 Your AI-powered standup agent is ready to go!\n');
}

main().catch((err) => {
  console.error('\n❌ Setup failed:', err.message);
  process.exit(1);
});