/**
 * scripts/setup.ts
 *
 * Unified setup script for Notion of Progress.
 * 
 * This script handles all setup tasks:
 *   1. Creates Notion databases (Task DB, Standup Log, System Status)
 *   2. Configures GitHub repository secrets for automated deployment
 *   3. Validates environment configuration
 *   4. Provides next steps and guidance
 *
 * Usage:
 *   mise run setup
 *   
 * Prerequisites:
 *   1. Create an integration at https://www.notion.com/my-integrations
 *   2. Create an empty page in Notion (e.g. "Notion of Progress")
 *   3. Connect your integration to that page: ··· → Connections
 *   4. Set NOTION_API_KEY and ANTHROPIC_API_KEY in .env
 *
 * The script will ask for the Notion page URL and handle the rest automatically.
 * It's idempotent - safe to run multiple times, only creates missing resources.
 */

import 'dotenv/config';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createInterface } from 'readline';
import { Client } from '@notionhq/client';

// We'll call the existing setup-notion script via subprocess to avoid import complexity

// Dashboard icons for status pages
const DASHBOARD_ICONS = ['🚀', '💻', '⚡', '🔧', '📊', '🤖', '⚙️', '💡', '🎯', '🔥'] as const;

function randomDashboardIcon(): string {
  return DASHBOARD_ICONS[Math.floor(Math.random() * DASHBOARD_ICONS.length)];
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ENV_PATH = join(ROOT, '.env');

interface SecretConfig {
  name: string;
  value: string | undefined;
  required: boolean;
  description: string;
}

function prompt(question: string): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function extractPageId(input: string): string {
  // Handle full Notion URLs: https://www.notion.so/Page-Title-abc123def456
  // or bare UUIDs: abc123de-f456-...
  const urlMatch = input.match(/([a-f0-9]{32})(?:\?|$)/i) || input.match(/([a-f0-9-]{36})(?:\?|$)/i);
  if (urlMatch) return urlMatch[1].replace(/-/g, '');
  // Try stripping dashes from bare UUID
  const bare = input.replace(/-/g, '');
  if (/^[a-f0-9]{32}$/i.test(bare)) return bare;
  throw new Error(`Could not extract a page ID from: "${input}"`);
}

function updateEnv(key: string, value: string): void {
  let content = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, 'utf8') : '';
  const line = `${key}=${value}`;
  const regex = new RegExp(`^#?\\s*${key}=.*`, 'm');

  if (regex.test(content)) {
    content = content.replace(regex, line);
  } else {
    content = content.trimEnd() + `\n${line}\n`;
  }

  writeFileSync(ENV_PATH, content, 'utf8');
}

function getRequiredSecrets(): SecretConfig[] {
  return [
    {
      name: 'NOTION_API_KEY',
      value: process.env.NOTION_API_KEY,
      required: true,
      description: 'Notion integration token from https://www.notion.com/my-integrations'
    },
    {
      name: 'ANTHROPIC_API_KEY', 
      value: process.env.ANTHROPIC_API_KEY,
      required: true,
      description: 'Anthropic API key from https://console.anthropic.com/settings/keys'
    },
    {
      name: 'NOTION_TASK_DB_ID',
      value: process.env.NOTION_TASK_DB_ID,
      required: true,
      description: 'Task database ID (auto-generated by setup script)'
    },
    {
      name: 'NOTION_STANDUP_LOG_DB_ID',
      value: process.env.NOTION_STANDUP_LOG_DB_ID,
      required: true,
      description: 'Standup log database ID (auto-generated by setup script)'
    },
    {
      name: 'NOTION_SYSTEM_STATUS_DB_ID',
      value: process.env.NOTION_SYSTEM_STATUS_DB_ID,
      required: true,
      description: 'System status database ID (auto-generated by setup script)'
    },
    {
      name: 'DISCORD_WEBHOOK_URL',
      value: process.env.DISCORD_WEBHOOK_URL,
      required: false,
      description: 'Discord webhook URL for notifications (optional)'
    }
  ];
}

async function checkGitHubCLI(): Promise<boolean> {
  try {
    const { execSync } = await import('child_process');
    execSync('gh --version', { stdio: 'ignore' });
    // Check if authenticated
    execSync('gh auth status', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

async function checkGitHubRepo(): Promise<{ owner: string; repo: string } | null> {
  try {
    const { execSync } = await import('child_process');
    const remoteUrl = execSync('git remote get-url origin', { encoding: 'utf8' }).trim();
    
    // Parse GitHub URL (both HTTPS and SSH formats)
    const httpsMatch = remoteUrl.match(/https:\/\/github\.com\/([^\/]+)\/([^\/]+?)(?:\.git)?$/);
    const sshMatch = remoteUrl.match(/git@github\.com:([^\/]+)\/([^\/]+?)(?:\.git)?$/);
    
    if (httpsMatch) {
      return { owner: httpsMatch[1], repo: httpsMatch[2] };
    } else if (sshMatch) {
      return { owner: sshMatch[1], repo: sshMatch[2] };
    }
    
    return null;
  } catch {
    return null;
  }
}

async function setSecretsViaGitHubCLI(secrets: SecretConfig[]): Promise<boolean> {
  try {
    const { execSync } = await import('child_process');
    
    console.log('\n🔐 Setting up GitHub secrets...\n');
    
    let allSuccessful = true;
    
    for (const secret of secrets) {
      if (!secret.value) {
        if (secret.required) {
          console.log(`❌ Required secret ${secret.name} is missing from .env`);
          allSuccessful = false;
        } else {
          console.log(`⏭️  Skipping optional secret ${secret.name} (not set in .env)`);
        }
        continue;
      }

      try {
        // Use stdin to avoid command injection via secret values
        execSync(`gh secret set ${secret.name}`, {
          input: secret.value,
          stdio: ['pipe', 'pipe', 'pipe'],
          encoding: 'utf8'
        });
        console.log(`  ✅ ${secret.name}`);
      } catch (error) {
        console.log(`  ❌ Failed to set ${secret.name}`);
        allSuccessful = false;
      }
    }
    
    return allSuccessful;
  } catch {
    return false;
  }
}

function printManualSecretsInstructions(secrets: SecretConfig[], repoInfo: { owner: string; repo: string } | null): void {
  console.log('\n📖 Manual GitHub Secrets Setup Required\n');
  
  if (repoInfo) {
    console.log(`🔗 Repository: https://github.com/${repoInfo.owner}/${repoInfo.repo}`);
    console.log(`🔧 Secrets URL: https://github.com/${repoInfo.owner}/${repoInfo.repo}/settings/secrets/actions\n`);
  } else {
    console.log('🔧 Go to your GitHub repository → Settings → Secrets and variables → Actions\n');
  }
  
  console.log('📋 Add these repository secrets:\n');
  
  for (const secret of secrets) {
    const status = secret.value ? '✅' : (secret.required ? '❌' : '⏭️');
    const value = secret.value || (secret.required ? 'MISSING - CHECK .env' : 'Not set (optional)');
    
    console.log(`${status} ${secret.name}`);
    console.log(`   Description: ${secret.description}`);
    console.log(`   Value: ${secret.value ? '***[HIDDEN]***' : value}`);
    console.log('');
  }
  
  console.log('💻 GitHub CLI Commands (if you prefer):\n');
  
  for (const secret of secrets) {
    if (secret.value) {
      console.log(`echo "***" | gh secret set ${secret.name}`);
    } else if (secret.required) {
      console.log(`# ${secret.name} - MISSING FROM .env`);
    } else {
      console.log(`# echo "your_value_here" | gh secret set ${secret.name}  # Optional`);
    }
  }
}

async function runNotionSetup(): Promise<void> {
  console.log('📖 STEP 1: Notion Databases Setup\n');
  
  // Import and run the existing setup-notion functionality
  // We'll shell out to the existing script to avoid duplicating logic
  const { execSync } = await import('child_process');
  
  try {
    execSync('npx tsx scripts/setup-notion.ts', { 
      stdio: 'inherit',
      cwd: ROOT 
    });
    console.log('\n✅ Notion databases setup complete!');
  } catch (error) {
    throw new Error(`Notion setup failed: ${error}`);
  }
}

async function setupGitHubSecrets(): Promise<void> {
  // Check if we have a GitHub repository
  const repoInfo = await checkGitHubRepo();
  if (!repoInfo) {
    console.log('\n⚠️  No GitHub repository detected. GitHub Actions setup skipped.');
    console.log('   To enable automated standups, push your code to GitHub first.\n');
    return;
  }

  console.log(`\n🐙 GitHub repository detected: ${repoInfo.owner}/${repoInfo.repo}`);

  // Get secrets configuration - this will include the fresh database IDs
  const secrets = getRequiredSecrets();
  const missingRequired = secrets.filter(s => s.required && !s.value);

  if (missingRequired.length > 0) {
    console.log('\n❌ Cannot set up GitHub secrets - missing required environment variables.');
    printManualSecretsInstructions(secrets, repoInfo);
    return;
  }

  // Check GitHub CLI availability
  const hasGitHubCLI = await checkGitHubCLI();
  
  if (hasGitHubCLI) {
    console.log('\n🔧 GitHub CLI detected. Setting up repository secrets automatically...');
    const success = await setSecretsViaGitHubCLI(secrets);
    
    if (success) {
      console.log('\n🎉 GitHub secrets setup complete!');
      console.log('\n📋 Your automated workflows are now ready:');
      console.log('   📅 Daily standups: Weekdays at 8 AM EST');
      console.log('   📊 Weekly digest: Fridays at 5 PM EST');
      console.log('\n🧪 Test your setup:');
      console.log('   1. Go to Actions tab in your GitHub repo');
      console.log('   2. Select "Daily Standup Automation"');
      console.log('   3. Click "Run workflow" to test manually');
    } else {
      console.log('\n⚠️  Some secrets failed to set. Please check manually:');
      printManualSecretsInstructions(secrets, repoInfo);
    }
  } else {
    console.log('\n📖 GitHub CLI not available. Manual setup required for automated deployment:');
    printManualSecretsInstructions(secrets, repoInfo);
    console.log('\n💡 Setup GitHub CLI:');
    console.log('   1. Install: brew install gh (macOS) or npm install -g @github/cli');
    console.log('   2. Authenticate: gh auth login');
    console.log('   3. Re-run setup to configure secrets automatically');
  }
}

async function main(): Promise<void> {
  console.log('\n🚀 Notion of Progress — Complete Setup\n');

  // Check for required API keys first
  if (!process.env.NOTION_API_KEY || !process.env.ANTHROPIC_API_KEY) {
    console.log('❌ Missing required API keys in .env file:\n');
    if (!process.env.NOTION_API_KEY) {
      console.log('   NOTION_API_KEY - Get from https://www.notion.com/my-integrations');
    }
    if (!process.env.ANTHROPIC_API_KEY) {
      console.log('   ANTHROPIC_API_KEY - Get from https://console.anthropic.com/settings/keys');
    }
    console.log('\nAdd these to your .env file and run setup again.\n');
    process.exit(1);
  }

  // Step 1: Setup Notion databases using existing script
  await runNotionSetup();

  // Step 2: Setup GitHub secrets for automation
  console.log('\n🚀 STEP 2: GitHub Actions Setup');
  await setupGitHubSecrets();

  // Final instructions
  console.log('\n✅ SETUP COMPLETE!\n');
  console.log('🎯 Next Steps:');
  console.log('   1. Run your first standup: mise run standup');
  console.log('   2. Check your System Status dashboard in Notion');
  console.log('   3. Make the System Status page public (optional)');
  console.log('   4. Test GitHub Actions workflows (if configured)');
  console.log('\n🔥 Your AI-powered standup agent is ready to go!\n');
}

main().catch((err) => {
  console.error('\n❌ Setup failed:', err.message);
  process.exit(1);
});