/**
 * Enum for task status values used throughout the system.
 * These match the Notion database status property options.
 */
export enum TaskStatus {
  TODO = 'To Do',
  IN_PROGRESS = 'In Progress', 
  DONE = 'Done',
  BLOCKED = 'Blocked',
}

/**
 * Enum for task priority levels.
 * These match the Notion database priority property options.
 */
export enum TaskPriority {
  HIGH = 'High',
  MEDIUM = 'Medium',
  LOW = 'Low',
}

/**
 * Represents a task summary with all essential information.
 * This is the primary data structure used throughout the application.
 */
export interface TaskSummary {
  /** Unique identifier for the task (Notion page ID) */
  id: string;
  /** Human-readable title of the task */
  title: string;
  /** Current status of the task */
  status: TaskStatus;
  /** Due date in ISO string format, or null if not set */
  dueDate: string | null;
  /** Priority level, or null if not set */
  priority: TaskPriority | null;
  /** Last edited timestamp in ISO format */
  lastEdited: string;
  /** Direct URL to the task in Notion */
  url: string;
}

/**
 * Represents a single bullet point in a standup summary.
 */
export interface StandupBullet {
  /** The text content of the bullet point */
  text: string;
  /** Optional reference to the associated task ID */
  taskId?: string;
}

/**
 * Complete standup summary structure containing all sections.
 * This is generated by the AI and used to create the standup page.
 */
export interface StandupSummary {
  /** Tasks completed yesterday */
  yesterday: StandupBullet[];
  /** Tasks planned for today */
  today: StandupBullet[];
  /** Current blockers preventing progress */
  blockers: StandupBullet[];
}
