/**
 * McpDigestAgent
 *
 * Every Friday, reads the week's standup pages from the Standup Log DB via
 * Notion MCP, synthesizes them into a weekly digest using Claude, and writes
 * the digest page back — completing a full autonomous read/write loop.
 *
 * This is the key story: Claude reads the pages it wrote all week and reflects
 * on them, producing a summary no human had to assemble.
 */

import { query } from '@anthropic-ai/claude-agent-sdk';
import { config } from '../../config/index';
import { todayISO } from '../../utils/dateHelpers';
import { logger } from '../../utils/logger';
import { notifyDiscord } from '../discord/DiscordNotifier';

const DIGEST_ICONS = [
  '📅', '📊', '🗓️', '📋', '🔭', '🧭', '📈', '🏁', '🎯', '🌟',
];

function randomIcon(): string {
  return DIGEST_ICONS[Math.floor(Math.random() * DIGEST_ICONS.length)];
}

function weekRange(): { start: string; end: string; label: string } {
  const today = new Date();
  const dayOfWeek = today.getDay(); // 0=Sun, 1=Mon, ..., 5=Fri
  const monday = new Date(today);
  monday.setDate(today.getDate() - (dayOfWeek === 0 ? 6 : dayOfWeek - 1));
  const friday = new Date(monday);
  friday.setDate(monday.getDate() + 4);

  const fmt = (d: Date) =>
    d.toLocaleDateString('en-CA', { timeZone: process.env.TZ ?? 'America/New_York' });
  const label = (d: Date) =>
    d.toLocaleDateString('en-US', {
      timeZone: process.env.TZ ?? 'America/New_York',
      month: 'short',
      day: 'numeric',
    });

  return {
    start: fmt(monday),
    end: fmt(friday),
    label: `${label(monday)} – ${label(friday)}`,
  };
}

function buildDigestPrompt(icon: string): string {
  const { start, end, label } = weekRange();
  const today = todayISO();

  return `You are writing a weekly digest page in Notion. Today is ${today}.

STANDUP LOG DB ID: ${config.notion.standupLogDbId}

STEP 1 — Read this week's standups:
Query the Standup Log DB for pages where Date is between "${start}" and "${end}" (inclusive) and Status = "Generated".
For each page found, read its block content to extract the Yesterday, Today, and Blockers sections.

STEP 2 — Synthesize a weekly digest:
Based on what you read, identify:
- Key wins and completed work across the week
- Main focus areas (recurring themes in "Today" sections)
- Any recurring or unresolved blockers
- A "week in numbers" summary (total standups, total tasks mentioned, blocker count)

STEP 3 — Write the digest page:
Create a new page in the Standup Log DB with:
- Title: "Weekly Digest · ${label}"
- Icon: emoji "${icon}"
- Date: ${today}
- Status: "Generated"
- Tasks Reviewed: 0

PAGE CONTENT (use these exact blocks in order):
1. A callout block with icon 📅, gray_background, text: "Week of ${label}"
2. A divider block
3. A callout block with icon 🏆, yellow_background, text: "Wins This Week"
4. Bulleted list items for key wins (3–5 bullets, each referencing specific work completed)
5. A callout block with icon 🎯, blue_background, text: "Focus Areas"
6. Bulleted list items for recurring themes and focus areas (2–4 bullets)
7. A callout block with icon 🚧, ${`red_background`}, text: "Recurring Blockers"
8. Bulleted list items for any blockers that appeared more than once, or "No recurring blockers this week." if none
9. A callout block with icon 📊, gray_background, text: "Week in Numbers"
10. Bulleted list items with stats: standups generated, total tasks mentioned, blockers raised
11. A divider block
12. A paragraph block (italic, gray): "Generated by Notion of Progress · Weekly Digest · ${new Date().toLocaleTimeString()}"

When done, output the URL of the digest page.`;
}

export async function runMcpDigestAgent({ verbose = false, dryRun = false } = {}): Promise<string> {
  const { label } = weekRange();
  logger.info(`Starting weekly digest agent for week of ${label}${dryRun ? ' (dry run)' : ''}`);

  if (dryRun) {
    const { start, end } = weekRange();
    process.stdout.write(`\n\x1b[1m─── Dry Run Preview ───────────────────────────────────────\x1b[0m\n\n`);
    process.stdout.write(`\x1b[1m📅 Weekly Digest\x1b[0m  Week of ${label}\n`);
    process.stdout.write(`  Would read standup pages from ${start} to ${end}\n`);
    process.stdout.write(`  Would synthesize wins, focus areas, recurring blockers\n`);
    process.stdout.write(`  Would write a digest page to the Standup Log DB\n\n`);
    process.stdout.write(`\x1b[1m[DRY RUN]\x1b[0m Nothing was written to Notion.\n\n`);
    return '';
  }

  const icon = randomIcon();
  let digestUrl = '';
  let lastResult = '';

  if (verbose) process.stdout.write('\n');

  for await (const message of query({
    prompt: buildDigestPrompt(icon),
    options: {
      model: 'claude-opus-4-6',
      mcpServers: {
        notion: {
          command: 'npx',
          args: ['-y', '@notionhq/notion-mcp-server'],
          env: {
            OPENAPI_MCP_HEADERS: JSON.stringify({
              Authorization: `Bearer ${config.notion.apiKey}`,
              'Notion-Version': '2022-06-28',
            }),
          },
        },
      },
      allowedTools: ['mcp__notion__*'],
      permissionMode: 'acceptEdits',
      maxTurns: 30,
    },
  })) {
    if (message.type === 'assistant' && Array.isArray(message.message?.content)) {
      for (const block of message.message.content) {
        if (verbose && block.type === 'text' && block.text) {
          process.stdout.write(`💭 \x1b[1m[Claude]\x1b[0m ${block.text.trim()}\n\n`);
        } else if (verbose && block.type === 'tool_use') {
          const action = (block.name as string)
            .replace(/^mcp__\w+__/, '')
            .replace(/^API-/, '')
            .replace(/-/g, ' ')
            .replace(/\b\w/g, (c) => c.toUpperCase());
          process.stdout.write(`🔧 \x1b[1m[MCP]\x1b[0m \x1b[1m[NOTION API]\x1b[0m ${action}\n`);
        }
      }
    } else if ('result' in message) {
      const result = typeof message.result === 'string' ? message.result : '';
      lastResult = result;
      const urlMatch = result.match(/https:\/\/www\.notion\.so\/[^\s)>\]"]+/);
      if (urlMatch) digestUrl = urlMatch[0];
    }
  }

  if (verbose) process.stdout.write('\n');

  if (!digestUrl) {
    logger.warn(`Digest agent completed but no URL found. Raw result: ${lastResult.slice(0, 500)}`);
    throw new Error('Digest agent completed but no digest URL was found in the output');
  }

  logger.info(`Weekly digest written: ${digestUrl}`);

  if (config.discord.webhookUrl) {
    await notifyDiscordDigest(label, digestUrl);
  }

  return digestUrl;
}

async function notifyDiscordDigest(weekLabel: string, url: string): Promise<void> {
  if (!config.discord.webhookUrl) return;

  const body = {
    embeds: [{
      title: `📅 Weekly Digest · ${weekLabel}`,
      color: 0x9b59b6,
      description: 'Your weekly summary is ready in Notion — wins, focus areas, and recurring blockers from the week.',
      url,
      footer: { text: 'Generated by Notion of Progress' },
    }],
  };

  const response = await fetch(config.discord.webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const text = await response.text();
    logger.warn(`Discord digest notification failed: ${response.status} ${text}`);
    return;
  }

  logger.info('Discord digest notification sent');
}
