/**
 * McpStandupAgent
 *
 * Hybrid pipeline that combines the reliability of the typed Notion client
 * with the power of the Claude Agent SDK + Notion MCP for autonomous page writing.
 *
 * Split of responsibilities:
 *   - NotionTaskRepository    → fetches tasks reliably via @notionhq/client
 *   - ClaudeSummaryGenerator  → generates the standup summary JSON
 *   - MCP agent               → autonomously writes the standup page via Notion MCP
 */

import { query } from '@anthropic-ai/claude-agent-sdk';
import { config } from '../../config/index';
import { todayISO, todayFormatted, yesterdayISO } from '../../utils/dateHelpers';
import { logger } from '../../utils/logger';
import type { TaskSummary, StandupSummary } from '../../core/domain/types';
import { NotionTaskRepository } from '../notion/NotionTaskRepository';
import { ClaudeSummaryGenerator } from '../claude/ClaudeSummaryGenerator';

// ─── Phase 3: write the standup page via MCP ─────────────────────────────────

function buildWritePrompt(
  summary: StandupSummary,
  completed: TaskSummary[],
  active: TaskSummary[],
): string {
  const fmt = (bullets: Array<{ text: string; taskId?: string }>) =>
    bullets.length > 0
      ? bullets.map((b) => {
          const task = b.taskId ? [...completed, ...active].find((t) => t.id === b.taskId) : undefined;
          return `  - ${b.text}${task ? ` (${task.url})` : ''}`;
        }).join('\n')
      : '  - Nothing to report.';

  return `Write today's standup page in Notion using the following data.

STANDUP LOG DB ID: ${config.notion.standupLogDbId}
TODAY: ${todayISO()}

First, query the Standup Log DB to check if a page already exists with Date = "${todayISO()}".
- If it exists, update its blocks (delete old blocks and append new ones) and update its properties.
- If not, create a new page.

PAGE PROPERTIES:
- Title: "Standup · ${todayFormatted()}"
- Date: ${todayISO()}
- Status: "Generated"
- Tasks Reviewed: ${completed.length + active.length}

PAGE CONTENT (use these exact blocks in order):
1. A callout block with icon 📊, gray_background color, text: "${completed.length} completed · ${active.length} active · ${summary.blockers.length} blocker${summary.blockers.length !== 1 ? 's' : ''}"
2. A divider block
3. A callout block with icon ✅, green_background color, text: "Yesterday"
4. Bulleted list items for Yesterday:
${fmt(summary.yesterday)}
5. A callout block with icon 🔨, blue_background color, text: "Today"
6. Bulleted list items for Today:
${fmt(summary.today)}
7. A callout block with icon 🚧, ${summary.blockers.length > 0 ? 'red_background' : 'gray_background'} color, text: "Blockers"
8. Bulleted list items for Blockers:
${fmt(summary.blockers)}
9. A divider block
10. A paragraph block (italic, gray): "Generated by Notion of Progress · ${new Date().toLocaleTimeString()}"

When done, output the URL of the standup page.`;
}

async function writeStandupViaMcp(
  summary: StandupSummary,
  completed: TaskSummary[],
  active: TaskSummary[],
  verbose: boolean,
): Promise<string> {
  logger.info('Writing standup page via Notion MCP');

  let standupUrl = '';

  if (verbose) process.stdout.write('\n');

  for await (const message of query({
    prompt: buildWritePrompt(summary, completed, active),
    options: {
      model: 'claude-opus-4-6',
      mcpServers: {
        notion: {
          command: 'npx',
          args: ['-y', '@notionhq/notion-mcp-server'],
          env: {
            OPENAPI_MCP_HEADERS: JSON.stringify({
              Authorization: `Bearer ${config.notion.apiKey}`,
              'Notion-Version': '2022-06-28',
            }),
          },
        },
      },
      allowedTools: ['mcp__notion__*'],
      permissionMode: 'acceptEdits',
      maxTurns: 20,
    },
  })) {
    if (message.type === 'assistant' && Array.isArray(message.message?.content)) {
      for (const block of message.message.content) {
        if (verbose && block.type === 'text' && block.text) {
          process.stdout.write(`💭 ${block.text}\n`);
        } else if (verbose && block.type === 'tool_use') {
          process.stdout.write(`🔧 ${block.name}\n`);
        }
      }
    } else if ('result' in message) {
      const result = message.result ?? '';
      const urlMatch = result.match(/https:\/\/www\.notion\.so\/[^\s)>\]"]+/);
      if (urlMatch) standupUrl = urlMatch[0];
    }
  }

  if (verbose) process.stdout.write('\n');

  if (!standupUrl) {
    throw new Error('MCP agent completed but no standup URL was found in the output');
  }

  return standupUrl;
}

// ─── Entry point ─────────────────────────────────────────────────────────────

export async function runMcpStandupAgent({ verbose = false } = {}): Promise<string> {
  logger.info('Starting Notion MCP standup agent');

  // Phase 1: fetch tasks via typed Notion client (reliable)
  logger.info('Fetching tasks');
  const taskRepo = new NotionTaskRepository();
  const { completed, active } = await taskRepo.fetchTasks();
  logger.info(`Tasks fetched — completed: ${completed.length}, active: ${active.length}`);

  // Phase 2: generate summary with Claude
  logger.info('Generating standup summary');
  const summarizer = new ClaudeSummaryGenerator();
  const summary: StandupSummary = await summarizer.generateSummary(completed, active);

  // Phase 3: write the page autonomously via Notion MCP
  return writeStandupViaMcp(summary, completed, active, verbose);
}
