name: Integration

on:
  pull_request:

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true

      - name: Install dependencies
        run: mise run install

      - name: Typecheck
        run: mise run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true

      - name: Install dependencies
        run: mise run install

      - name: Test
        run: mise run test
